'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Database1")>  _
Partial Public Class DataClasses1DataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertEquipmentTables(instance As EquipmentTables)
    End Sub
  Partial Private Sub UpdateEquipmentTables(instance As EquipmentTables)
    End Sub
  Partial Private Sub DeleteEquipmentTables(instance As EquipmentTables)
    End Sub
  Partial Private Sub Insertstock(instance As stock)
    End Sub
  Partial Private Sub Updatestock(instance As stock)
    End Sub
  Partial Private Sub Deletestock(instance As stock)
    End Sub
  Partial Private Sub InsertTableID(instance As TableID)
    End Sub
  Partial Private Sub UpdateTableID(instance As TableID)
    End Sub
  Partial Private Sub DeleteTableID(instance As TableID)
    End Sub
  Partial Private Sub Insertสถานะ(instance As สถานะ)
    End Sub
  Partial Private Sub Updateสถานะ(instance As สถานะ)
    End Sub
  Partial Private Sub Deleteสถานะ(instance As สถานะ)
    End Sub
  Partial Private Sub InsertMail(instance As Mail)
    End Sub
  Partial Private Sub UpdateMail(instance As Mail)
    End Sub
  Partial Private Sub DeleteMail(instance As Mail)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("Database1ConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property EquipmentTables() As System.Data.Linq.Table(Of EquipmentTables)
		Get
			Return Me.GetTable(Of EquipmentTables)
		End Get
	End Property
	
	Public ReadOnly Property stocks() As System.Data.Linq.Table(Of stock)
		Get
			Return Me.GetTable(Of stock)
		End Get
	End Property
	
	Public ReadOnly Property TableIDs() As System.Data.Linq.Table(Of TableID)
		Get
			Return Me.GetTable(Of TableID)
		End Get
	End Property
	
	Public ReadOnly Property สถานะs() As System.Data.Linq.Table(Of สถานะ)
		Get
			Return Me.GetTable(Of สถานะ)
		End Get
	End Property
	
	Public ReadOnly Property Mails() As System.Data.Linq.Table(Of Mail)
		Get
			Return Me.GetTable(Of Mail)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Equipment")>  _
Partial Public Class EquipmentTables
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Equipment_Id As Integer
	
	Private _ชื่ออุปกรณ์ As String
	
	Private _รายละเอียดอุปกรณ์ As String
	
	Private _user_username As String
	
	Private _เบอร์โทรติดต่อเจ้าของ As String
	
	Private _ชื่อช่างซ่อม As String
	
	Private _username_Employee As String
	
	Private _รายละเอียดการซ่อม As String
	
	Private _ราคาซ่อม As String
	
	Private _สถานะซ่อม As String
	
	Private _วันที่ได้รับสินค้า As String
	
	Private _วันที่คาดว่าจะสินค้าแล้วเสร็จ As String
	
	Private _หมายเหตุ As String
	
	Private _Pic As String
	
	Private _EquipmentCode As String
	
	Private _ราคาประเมิน As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnEquipment_IdChanging(value As Integer)
    End Sub
    Partial Private Sub OnEquipment_IdChanged()
    End Sub
    Partial Private Sub Onชื่ออุปกรณ์Changing(value As String)
    End Sub
    Partial Private Sub Onชื่ออุปกรณ์Changed()
    End Sub
    Partial Private Sub Onรายละเอียดอุปกรณ์Changing(value As String)
    End Sub
    Partial Private Sub Onรายละเอียดอุปกรณ์Changed()
    End Sub
    Partial Private Sub Onuser_usernameChanging(value As String)
    End Sub
    Partial Private Sub Onuser_usernameChanged()
    End Sub
    Partial Private Sub Onเบอร์โทรติดต่อเจ้าของChanging(value As String)
    End Sub
    Partial Private Sub Onเบอร์โทรติดต่อเจ้าของChanged()
    End Sub
    Partial Private Sub Onชื่อช่างซ่อมChanging(value As String)
    End Sub
    Partial Private Sub Onชื่อช่างซ่อมChanged()
    End Sub
    Partial Private Sub Onusername_EmployeeChanging(value As String)
    End Sub
    Partial Private Sub Onusername_EmployeeChanged()
    End Sub
    Partial Private Sub Onรายละเอียดการซ่อมChanging(value As String)
    End Sub
    Partial Private Sub Onรายละเอียดการซ่อมChanged()
    End Sub
    Partial Private Sub Onราคาซ่อมChanging(value As String)
    End Sub
    Partial Private Sub Onราคาซ่อมChanged()
    End Sub
    Partial Private Sub Onสถานะซ่อมChanging(value As String)
    End Sub
    Partial Private Sub Onสถานะซ่อมChanged()
    End Sub
    Partial Private Sub Onวันที่ได้รับสินค้าChanging(value As String)
    End Sub
    Partial Private Sub Onวันที่ได้รับสินค้าChanged()
    End Sub
    Partial Private Sub Onวันที่คาดว่าจะสินค้าแล้วเสร็จChanging(value As String)
    End Sub
    Partial Private Sub Onวันที่คาดว่าจะสินค้าแล้วเสร็จChanged()
    End Sub
    Partial Private Sub OnหมายเหตุChanging(value As String)
    End Sub
    Partial Private Sub OnหมายเหตุChanged()
    End Sub
    Partial Private Sub OnPicChanging(value As String)
    End Sub
    Partial Private Sub OnPicChanged()
    End Sub
    Partial Private Sub OnEquipmentCodeChanging(value As String)
    End Sub
    Partial Private Sub OnEquipmentCodeChanged()
    End Sub
    Partial Private Sub OnราคาประเมินChanging(value As String)
    End Sub
    Partial Private Sub OnราคาประเมินChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Equipment_Id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property Equipment_Id() As Integer
		Get
			Return Me._Equipment_Id
		End Get
		Set
			If ((Me._Equipment_Id = value)  _
						= false) Then
				Me.OnEquipment_IdChanging(value)
				Me.SendPropertyChanging
				Me._Equipment_Id = value
				Me.SendPropertyChanged("Equipment_Id")
				Me.OnEquipment_IdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ชื่ออุปกรณ์", DbType:="NVarChar(MAX)")>  _
	Public Property ชื่ออุปกรณ์() As String
		Get
			Return Me._ชื่ออุปกรณ์
		End Get
		Set
			If (String.Equals(Me._ชื่ออุปกรณ์, value) = false) Then
				Me.Onชื่ออุปกรณ์Changing(value)
				Me.SendPropertyChanging
				Me._ชื่ออุปกรณ์ = value
				Me.SendPropertyChanged("ชื่ออุปกรณ์")
				Me.Onชื่ออุปกรณ์Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_รายละเอียดอุปกรณ์", DbType:="NVarChar(MAX)")>  _
	Public Property รายละเอียดอุปกรณ์() As String
		Get
			Return Me._รายละเอียดอุปกรณ์
		End Get
		Set
			If (String.Equals(Me._รายละเอียดอุปกรณ์, value) = false) Then
				Me.Onรายละเอียดอุปกรณ์Changing(value)
				Me.SendPropertyChanging
				Me._รายละเอียดอุปกรณ์ = value
				Me.SendPropertyChanged("รายละเอียดอุปกรณ์")
				Me.Onรายละเอียดอุปกรณ์Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_username", DbType:="NVarChar(MAX)")>  _
	Public Property user_username() As String
		Get
			Return Me._user_username
		End Get
		Set
			If (String.Equals(Me._user_username, value) = false) Then
				Me.Onuser_usernameChanging(value)
				Me.SendPropertyChanging
				Me._user_username = value
				Me.SendPropertyChanged("user_username")
				Me.Onuser_usernameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_เบอร์โทรติดต่อเจ้าของ", DbType:="NVarChar(MAX)")>  _
	Public Property เบอร์โทรติดต่อเจ้าของ() As String
		Get
			Return Me._เบอร์โทรติดต่อเจ้าของ
		End Get
		Set
			If (String.Equals(Me._เบอร์โทรติดต่อเจ้าของ, value) = false) Then
				Me.Onเบอร์โทรติดต่อเจ้าของChanging(value)
				Me.SendPropertyChanging
				Me._เบอร์โทรติดต่อเจ้าของ = value
				Me.SendPropertyChanged("เบอร์โทรติดต่อเจ้าของ")
				Me.Onเบอร์โทรติดต่อเจ้าของChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ชื่อช่างซ่อม", DbType:="NVarChar(MAX)")>  _
	Public Property ชื่อช่างซ่อม() As String
		Get
			Return Me._ชื่อช่างซ่อม
		End Get
		Set
			If (String.Equals(Me._ชื่อช่างซ่อม, value) = false) Then
				Me.Onชื่อช่างซ่อมChanging(value)
				Me.SendPropertyChanging
				Me._ชื่อช่างซ่อม = value
				Me.SendPropertyChanged("ชื่อช่างซ่อม")
				Me.Onชื่อช่างซ่อมChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_username_Employee", DbType:="NVarChar(MAX)")>  _
	Public Property username_Employee() As String
		Get
			Return Me._username_Employee
		End Get
		Set
			If (String.Equals(Me._username_Employee, value) = false) Then
				Me.Onusername_EmployeeChanging(value)
				Me.SendPropertyChanging
				Me._username_Employee = value
				Me.SendPropertyChanged("username_Employee")
				Me.Onusername_EmployeeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_รายละเอียดการซ่อม", DbType:="NVarChar(MAX)")>  _
	Public Property รายละเอียดการซ่อม() As String
		Get
			Return Me._รายละเอียดการซ่อม
		End Get
		Set
			If (String.Equals(Me._รายละเอียดการซ่อม, value) = false) Then
				Me.Onรายละเอียดการซ่อมChanging(value)
				Me.SendPropertyChanging
				Me._รายละเอียดการซ่อม = value
				Me.SendPropertyChanged("รายละเอียดการซ่อม")
				Me.Onรายละเอียดการซ่อมChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ราคาซ่อม", DbType:="NVarChar(MAX)")>  _
	Public Property ราคาซ่อม() As String
		Get
			Return Me._ราคาซ่อม
		End Get
		Set
			If (String.Equals(Me._ราคาซ่อม, value) = false) Then
				Me.Onราคาซ่อมChanging(value)
				Me.SendPropertyChanging
				Me._ราคาซ่อม = value
				Me.SendPropertyChanged("ราคาซ่อม")
				Me.Onราคาซ่อมChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_สถานะซ่อม", DbType:="NVarChar(MAX)")>  _
	Public Property สถานะซ่อม() As String
		Get
			Return Me._สถานะซ่อม
		End Get
		Set
			If (String.Equals(Me._สถานะซ่อม, value) = false) Then
				Me.Onสถานะซ่อมChanging(value)
				Me.SendPropertyChanging
				Me._สถานะซ่อม = value
				Me.SendPropertyChanged("สถานะซ่อม")
				Me.Onสถานะซ่อมChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_วันที่ได้รับสินค้า", DbType:="NVarChar(MAX)")>  _
	Public Property วันที่ได้รับสินค้า() As String
		Get
			Return Me._วันที่ได้รับสินค้า
		End Get
		Set
			If (String.Equals(Me._วันที่ได้รับสินค้า, value) = false) Then
				Me.Onวันที่ได้รับสินค้าChanging(value)
				Me.SendPropertyChanging
				Me._วันที่ได้รับสินค้า = value
				Me.SendPropertyChanged("วันที่ได้รับสินค้า")
				Me.Onวันที่ได้รับสินค้าChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_วันที่คาดว่าจะสินค้าแล้วเสร็จ", DbType:="NVarChar(MAX)")>  _
	Public Property วันที่คาดว่าจะสินค้าแล้วเสร็จ() As String
		Get
			Return Me._วันที่คาดว่าจะสินค้าแล้วเสร็จ
		End Get
		Set
			If (String.Equals(Me._วันที่คาดว่าจะสินค้าแล้วเสร็จ, value) = false) Then
				Me.Onวันที่คาดว่าจะสินค้าแล้วเสร็จChanging(value)
				Me.SendPropertyChanging
				Me._วันที่คาดว่าจะสินค้าแล้วเสร็จ = value
				Me.SendPropertyChanged("วันที่คาดว่าจะสินค้าแล้วเสร็จ")
				Me.Onวันที่คาดว่าจะสินค้าแล้วเสร็จChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_หมายเหตุ", DbType:="NVarChar(MAX)")>  _
	Public Property หมายเหตุ() As String
		Get
			Return Me._หมายเหตุ
		End Get
		Set
			If (String.Equals(Me._หมายเหตุ, value) = false) Then
				Me.OnหมายเหตุChanging(value)
				Me.SendPropertyChanging
				Me._หมายเหตุ = value
				Me.SendPropertyChanged("หมายเหตุ")
				Me.OnหมายเหตุChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Pic", DbType:="NVarChar(MAX)")>  _
	Public Property Pic() As String
		Get
			Return Me._Pic
		End Get
		Set
			If (String.Equals(Me._Pic, value) = false) Then
				Me.OnPicChanging(value)
				Me.SendPropertyChanging
				Me._Pic = value
				Me.SendPropertyChanged("Pic")
				Me.OnPicChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EquipmentCode", DbType:="NVarChar(50)")>  _
	Public Property EquipmentCode() As String
		Get
			Return Me._EquipmentCode
		End Get
		Set
			If (String.Equals(Me._EquipmentCode, value) = false) Then
				Me.OnEquipmentCodeChanging(value)
				Me.SendPropertyChanging
				Me._EquipmentCode = value
				Me.SendPropertyChanged("EquipmentCode")
				Me.OnEquipmentCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ราคาประเมิน", DbType:="NVarChar(MAX)")>  _
	Public Property ราคาประเมิน() As String
		Get
			Return Me._ราคาประเมิน
		End Get
		Set
			If (String.Equals(Me._ราคาประเมิน, value) = false) Then
				Me.OnราคาประเมินChanging(value)
				Me.SendPropertyChanging
				Me._ราคาประเมิน = value
				Me.SendPropertyChanged("ราคาประเมิน")
				Me.OnราคาประเมินChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.stock")>  _
Partial Public Class stock
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Id As Integer
	
	Private _stock_type As String
	
	Private _stock_name As String
	
	Private _stock_model As String
	
	Private _stock_of_devices As System.Nullable(Of Integer)
	
	Private _stock_price As System.Nullable(Of Decimal)
	
	Private _stock_cost As System.Nullable(Of Decimal)
	
	Private _stock_Margin1 As System.Nullable(Of Decimal)
	
	Private _stock_model_name As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdChanged()
    End Sub
    Partial Private Sub Onstock_typeChanging(value As String)
    End Sub
    Partial Private Sub Onstock_typeChanged()
    End Sub
    Partial Private Sub Onstock_nameChanging(value As String)
    End Sub
    Partial Private Sub Onstock_nameChanged()
    End Sub
    Partial Private Sub Onstock_modelChanging(value As String)
    End Sub
    Partial Private Sub Onstock_modelChanged()
    End Sub
    Partial Private Sub Onstock_of_devicesChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onstock_of_devicesChanged()
    End Sub
    Partial Private Sub Onstock_priceChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub Onstock_priceChanged()
    End Sub
    Partial Private Sub Onstock_costChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub Onstock_costChanged()
    End Sub
    Partial Private Sub Onstock_Margin1Changing(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub Onstock_Margin1Changed()
    End Sub
    Partial Private Sub Onstock_model_nameChanging(value As String)
    End Sub
    Partial Private Sub Onstock_model_nameChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property Id() As Integer
		Get
			Return Me._Id
		End Get
		Set
			If ((Me._Id = value)  _
						= false) Then
				Me.OnIdChanging(value)
				Me.SendPropertyChanging
				Me._Id = value
				Me.SendPropertyChanged("Id")
				Me.OnIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_stock_type", DbType:="NVarChar(MAX)")>  _
	Public Property stock_type() As String
		Get
			Return Me._stock_type
		End Get
		Set
			If (String.Equals(Me._stock_type, value) = false) Then
				Me.Onstock_typeChanging(value)
				Me.SendPropertyChanging
				Me._stock_type = value
				Me.SendPropertyChanged("stock_type")
				Me.Onstock_typeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_stock_name", DbType:="NVarChar(MAX)")>  _
	Public Property stock_name() As String
		Get
			Return Me._stock_name
		End Get
		Set
			If (String.Equals(Me._stock_name, value) = false) Then
				Me.Onstock_nameChanging(value)
				Me.SendPropertyChanging
				Me._stock_name = value
				Me.SendPropertyChanged("stock_name")
				Me.Onstock_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_stock_model", DbType:="NVarChar(MAX)")>  _
	Public Property stock_model() As String
		Get
			Return Me._stock_model
		End Get
		Set
			If (String.Equals(Me._stock_model, value) = false) Then
				Me.Onstock_modelChanging(value)
				Me.SendPropertyChanging
				Me._stock_model = value
				Me.SendPropertyChanged("stock_model")
				Me.Onstock_modelChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_stock_of_devices", DbType:="Int")>  _
	Public Property stock_of_devices() As System.Nullable(Of Integer)
		Get
			Return Me._stock_of_devices
		End Get
		Set
			If (Me._stock_of_devices.Equals(value) = false) Then
				Me.Onstock_of_devicesChanging(value)
				Me.SendPropertyChanging
				Me._stock_of_devices = value
				Me.SendPropertyChanged("stock_of_devices")
				Me.Onstock_of_devicesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_stock_price", DbType:="SmallMoney")>  _
	Public Property stock_price() As System.Nullable(Of Decimal)
		Get
			Return Me._stock_price
		End Get
		Set
			If (Me._stock_price.Equals(value) = false) Then
				Me.Onstock_priceChanging(value)
				Me.SendPropertyChanging
				Me._stock_price = value
				Me.SendPropertyChanged("stock_price")
				Me.Onstock_priceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_stock_cost", DbType:="SmallMoney")>  _
	Public Property stock_cost() As System.Nullable(Of Decimal)
		Get
			Return Me._stock_cost
		End Get
		Set
			If (Me._stock_cost.Equals(value) = false) Then
				Me.Onstock_costChanging(value)
				Me.SendPropertyChanging
				Me._stock_cost = value
				Me.SendPropertyChanged("stock_cost")
				Me.Onstock_costChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_stock_Margin1", AutoSync:=AutoSync.Always, DbType:="SmallMoney", IsDbGenerated:=true, UpdateCheck:=UpdateCheck.Never)>  _
	Public Property stock_Margin1() As System.Nullable(Of Decimal)
		Get
			Return Me._stock_Margin1
		End Get
		Set
			If (Me._stock_Margin1.Equals(value) = false) Then
				Me.Onstock_Margin1Changing(value)
				Me.SendPropertyChanging
				Me._stock_Margin1 = value
				Me.SendPropertyChanged("stock_Margin1")
				Me.Onstock_Margin1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_stock_model_name", AutoSync:=AutoSync.Always, DbType:="NVarChar(MAX)", IsDbGenerated:=true, UpdateCheck:=UpdateCheck.Never)>  _
	Public Property stock_model_name() As String
		Get
			Return Me._stock_model_name
		End Get
		Set
			If (String.Equals(Me._stock_model_name, value) = false) Then
				Me.Onstock_model_nameChanging(value)
				Me.SendPropertyChanging
				Me._stock_model_name = value
				Me.SendPropertyChanged("stock_model_name")
				Me.Onstock_model_nameChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.TableID")>  _
Partial Public Class TableID
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _user_id As Integer
	
	Private _user_username As String
	
	Private _user_password As String
	
	Private _user_type As String
	
	Private _user_FnameLname As String
	
	Private _user_phonenumber As String
	
	Private _user_Address As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub Onuser_idChanging(value As Integer)
    End Sub
    Partial Private Sub Onuser_idChanged()
    End Sub
    Partial Private Sub Onuser_usernameChanging(value As String)
    End Sub
    Partial Private Sub Onuser_usernameChanged()
    End Sub
    Partial Private Sub Onuser_passwordChanging(value As String)
    End Sub
    Partial Private Sub Onuser_passwordChanged()
    End Sub
    Partial Private Sub Onuser_typeChanging(value As String)
    End Sub
    Partial Private Sub Onuser_typeChanged()
    End Sub
    Partial Private Sub Onuser_FnameLnameChanging(value As String)
    End Sub
    Partial Private Sub Onuser_FnameLnameChanged()
    End Sub
    Partial Private Sub Onuser_phonenumberChanging(value As String)
    End Sub
    Partial Private Sub Onuser_phonenumberChanged()
    End Sub
    Partial Private Sub Onuser_AddressChanging(value As String)
    End Sub
    Partial Private Sub Onuser_AddressChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property user_id() As Integer
		Get
			Return Me._user_id
		End Get
		Set
			If ((Me._user_id = value)  _
						= false) Then
				Me.Onuser_idChanging(value)
				Me.SendPropertyChanging
				Me._user_id = value
				Me.SendPropertyChanged("user_id")
				Me.Onuser_idChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_username", DbType:="NVarChar(MAX)")>  _
	Public Property user_username() As String
		Get
			Return Me._user_username
		End Get
		Set
			If (String.Equals(Me._user_username, value) = false) Then
				Me.Onuser_usernameChanging(value)
				Me.SendPropertyChanging
				Me._user_username = value
				Me.SendPropertyChanged("user_username")
				Me.Onuser_usernameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_password", DbType:="NVarChar(MAX)")>  _
	Public Property user_password() As String
		Get
			Return Me._user_password
		End Get
		Set
			If (String.Equals(Me._user_password, value) = false) Then
				Me.Onuser_passwordChanging(value)
				Me.SendPropertyChanging
				Me._user_password = value
				Me.SendPropertyChanged("user_password")
				Me.Onuser_passwordChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_type", DbType:="NVarChar(MAX)")>  _
	Public Property user_type() As String
		Get
			Return Me._user_type
		End Get
		Set
			If (String.Equals(Me._user_type, value) = false) Then
				Me.Onuser_typeChanging(value)
				Me.SendPropertyChanging
				Me._user_type = value
				Me.SendPropertyChanged("user_type")
				Me.Onuser_typeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_FnameLname", DbType:="NVarChar(MAX)")>  _
	Public Property user_FnameLname() As String
		Get
			Return Me._user_FnameLname
		End Get
		Set
			If (String.Equals(Me._user_FnameLname, value) = false) Then
				Me.Onuser_FnameLnameChanging(value)
				Me.SendPropertyChanging
				Me._user_FnameLname = value
				Me.SendPropertyChanged("user_FnameLname")
				Me.Onuser_FnameLnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_phonenumber", DbType:="NVarChar(MAX)")>  _
	Public Property user_phonenumber() As String
		Get
			Return Me._user_phonenumber
		End Get
		Set
			If (String.Equals(Me._user_phonenumber, value) = false) Then
				Me.Onuser_phonenumberChanging(value)
				Me.SendPropertyChanging
				Me._user_phonenumber = value
				Me.SendPropertyChanged("user_phonenumber")
				Me.Onuser_phonenumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_Address", DbType:="NVarChar(MAX)")>  _
	Public Property user_Address() As String
		Get
			Return Me._user_Address
		End Get
		Set
			If (String.Equals(Me._user_Address, value) = false) Then
				Me.Onuser_AddressChanging(value)
				Me.SendPropertyChanging
				Me._user_Address = value
				Me.SendPropertyChanged("user_Address")
				Me.Onuser_AddressChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.สถานะ")>  _
Partial Public Class สถานะ
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Id As Integer
	
	Private _สถานะ As String
	
	Private _ชนิดอุปกรณ์ As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdChanged()
    End Sub
    Partial Private Sub OnสถานะChanging(value As String)
    End Sub
    Partial Private Sub OnสถานะChanged()
    End Sub
    Partial Private Sub Onชนิดอุปกรณ์Changing(value As String)
    End Sub
    Partial Private Sub Onชนิดอุปกรณ์Changed()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property Id() As Integer
		Get
			Return Me._Id
		End Get
		Set
			If ((Me._Id = value)  _
						= false) Then
				Me.OnIdChanging(value)
				Me.SendPropertyChanging
				Me._Id = value
				Me.SendPropertyChanged("Id")
				Me.OnIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_สถานะ", DbType:="NVarChar(MAX)")>  _
	Public Property สถานะ() As String
		Get
			Return Me._สถานะ
		End Get
		Set
			If (String.Equals(Me._สถานะ, value) = false) Then
				Me.OnสถานะChanging(value)
				Me.SendPropertyChanging
				Me._สถานะ = value
				Me.SendPropertyChanged("สถานะ")
				Me.OnสถานะChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ชนิดอุปกรณ์", DbType:="NVarChar(MAX)")>  _
	Public Property ชนิดอุปกรณ์() As String
		Get
			Return Me._ชนิดอุปกรณ์
		End Get
		Set
			If (String.Equals(Me._ชนิดอุปกรณ์, value) = false) Then
				Me.Onชนิดอุปกรณ์Changing(value)
				Me.SendPropertyChanging
				Me._ชนิดอุปกรณ์ = value
				Me.SendPropertyChanged("ชนิดอุปกรณ์")
				Me.Onชนิดอุปกรณ์Changed
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Mail")>  _
Partial Public Class Mail
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Id As Integer
	
	Private _ชื่อผู้ส่ง As String
	
	Private _ติดต่อเรา_ข้อเสนอแนะ As String
	
	Private _คะแนน As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdChanged()
    End Sub
    Partial Private Sub Onชื่อผู้ส่งChanging(value As String)
    End Sub
    Partial Private Sub Onชื่อผู้ส่งChanged()
    End Sub
    Partial Private Sub Onติดต่อเรา_ข้อเสนอแนะChanging(value As String)
    End Sub
    Partial Private Sub Onติดต่อเรา_ข้อเสนอแนะChanged()
    End Sub
    Partial Private Sub OnคะแนนChanging(value As String)
    End Sub
    Partial Private Sub OnคะแนนChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property Id() As Integer
		Get
			Return Me._Id
		End Get
		Set
			If ((Me._Id = value)  _
						= false) Then
				Me.OnIdChanging(value)
				Me.SendPropertyChanging
				Me._Id = value
				Me.SendPropertyChanged("Id")
				Me.OnIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ชื่อผู้ส่ง", DbType:="NVarChar(MAX)")>  _
	Public Property ชื่อผู้ส่ง() As String
		Get
			Return Me._ชื่อผู้ส่ง
		End Get
		Set
			If (String.Equals(Me._ชื่อผู้ส่ง, value) = false) Then
				Me.Onชื่อผู้ส่งChanging(value)
				Me.SendPropertyChanging
				Me._ชื่อผู้ส่ง = value
				Me.SendPropertyChanged("ชื่อผู้ส่ง")
				Me.Onชื่อผู้ส่งChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[ติดต่อเรา/ข้อเสนอแนะ]", Storage:="_ติดต่อเรา_ข้อเสนอแนะ", DbType:="NVarChar(MAX)")>  _
	Public Property ติดต่อเรา_ข้อเสนอแนะ() As String
		Get
			Return Me._ติดต่อเรา_ข้อเสนอแนะ
		End Get
		Set
			If (String.Equals(Me._ติดต่อเรา_ข้อเสนอแนะ, value) = false) Then
				Me.Onติดต่อเรา_ข้อเสนอแนะChanging(value)
				Me.SendPropertyChanging
				Me._ติดต่อเรา_ข้อเสนอแนะ = value
				Me.SendPropertyChanged("ติดต่อเรา_ข้อเสนอแนะ")
				Me.Onติดต่อเรา_ข้อเสนอแนะChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_คะแนน", DbType:="NVarChar(MAX)")>  _
	Public Property คะแนน() As String
		Get
			Return Me._คะแนน
		End Get
		Set
			If (String.Equals(Me._คะแนน, value) = false) Then
				Me.OnคะแนนChanging(value)
				Me.SendPropertyChanging
				Me._คะแนน = value
				Me.SendPropertyChanged("คะแนน")
				Me.OnคะแนนChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
